### ISSUE TITLE
Open Environment Variables option

### ISSUE THREAD

**Issue by NotQuiteApex** [pbanj/Breadtools#10]
I have to edit my PATH a lot for stuff, a quick option would be nice so I don't have to trudge through Windows search and extra menus.

**Comment by pbanj** [comment]
Should be doable.

**Comment by pbanj** [comment]
added in dc45223916a3a8688b0aa538b62506925e2bc36b

https://github.com/pbanj/tools-menu/releases/tag/0.00069
