### ISSUE TITLE
[Suggestion] Bash here

### ISSUE THREAD

**Issue by Aluminite** [pbanj/Breadtools#2]
Windows 10 AU added Bash on Ubuntu on Windows, so it should be added here.

**Comment by pbanj** [comment]
ill prob add it after i get off my lazy ass and do a fresh install of windows. i have too many different types of bash installed right now

**Comment by pbanj** [comment]
done. it needs cmd for now but i will try and figure out a way to avoid that

**Comment by pbanj** [comment]
scratch that i was able to remove the need for cmd

**Comment by pbanj** [comment]
also i will eventually make bash a separate thing for those that dont want it
