### ISSUE TITLE
Explorer Restart does nothing

### ISSUE THREAD

**Issue by NotQuiteApex** [pbanj/Breadtools#5]
title

**Comment by NotQuiteApex** [comment]
Still doesn't work with the latest GUI commit after reinstall of tools.

**Comment by pbanj** [comment]
Fucking amazing turtle. 10/10

**Comment by TurtleP** [comment]
did you actually remove the registry keys and rerun the applier?

**Comment by pbanj** [comment]
I mean if you did it right it would replace the key. Sooo did you do it right?

**Comment by NotQuiteApex** [comment]
> did you actually remove the registry keys and rerun the applier?

I used the uninstall option in the GUI, which is what I assume does just that. I did not restart between applies though.

**Comment by pbanj** [comment]
Shouldn't need to restart. Shouldn't need to uninstall either unless he changed the name of the key

**Comment by TurtleP** [comment]
@pbanj I used the command for the registry you gave me, unless the registry type isn't correct? Running it through the `Run` dialog works fine.

**Comment by pbanj** [comment]
Look at the terminal branch and copy that shit.

**Comment by TurtleP** [comment]
that is what it's currently using

**Comment by pbanj** [comment]
Remember that the way it has to be for it to be merged into the registry and how it will look after are 2 different things. This is why I keep telling you to actively test/use what I have made, instead of trying to reinvent the wheel 😋

**Comment by NotQuiteApex** [comment]
PB sent me the proper key, the one that is installed by the GUI isn't formatted correctly.

Currently it's
`[HKEY_CLASSES_ROOT\Directory\ContextMenus\Tools\shell\5Restart Explorer\command]
@="\"C:/Windows/System32/cmd.exe\" /c \"taskkill /f /im explorer.exe & start explorer.exe\""`

When it should be
`[HKEY_CLASSES_ROOT\Directory\ContextMenus\Tools\shell\5Restart Explorer\command]
@="\"C:\\Windows\\System32\\cmd.exe\" /c \"taskkill /f /im explorer.exe & start explorer.exe\""`

**Comment by NotQuiteApex** [comment]
Keep in mind Windows uses \ as the directory separator, instead of /

:p

**Comment by pbanj** [comment]
Man he's really bad at copy and paste.

**Comment by TurtleP** [comment]
> 
> 
> Keep in mind Windows uses \ as the directory separator, instead of /
> 
> :p

Keep in mind, I would have been fine fixing this with the comment from 10 minutes ago.

**Comment by pbanj** [comment]
You will take our harassment, and you'll like it

**Comment by NotQuiteApex** [comment]
PB likes to stir the pot but I genuinely wasn't sure if you were aware, because to be totally honest it should be / instead of \\, I've made the same mistake, sorry if it came off as rude.
